language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.6
dist: trusty
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt clean coverageOn coverage test
  - sbt coverageOn coverageReport coverageAggregate codacyCoverage

notifications:
  email: false
